alloc_settings:
  motor:
    center: 'left_brick:ev3-ports:outB'
    left: 'left_brick:ev3-ports:outA'
    right: 'left_brick:ev3-ports:outD'

  color_sensor:
    center: 'left_brick:ev3-ports:in2'
    left: 'left_brick:ev3-ports:in1'
    right: 'left_brick:ev3-ports:in3'

  touch_sensor:
    left: 'right_brick:ev3-ports:in2'
    right: 'right_brick:ev3-ports:in3'
    rear: 'right_brick:ev3-ports:in1'

  ultrasonic_sensor:
    front: 'right_brick:ev3-ports:in4'
    rear: 'left_brick:ev3-ports:in4'

obstacle_settings:
  border_settings:
    border_depth: 15
    border_color: (255, 255, 255)

  lake_settings:
    border_width: 29
    inner_radius: 38
    lake_blue_color: (58, 166, 221)
    lake_blue_x: 137
    lake_blue_y: 922
    lake_green_color: (122, 182, 72)
    lake_green_x: 1052
    lake_green_y: 567
    lake_red_color: (201, 45, 57)
    lake_red_x: 397
    lake_red_y: 232

motor_settings:
  pixel_coasting_subtraction: 0.7
  degree_coasting_subtraction: 1.5


wheel_settings:
  circumference: 173
  spacing: 120