robots:
  robot1:
    motor:
      left: 'ev3-ports:outA'
      right: 'ev3-ports:outD'

    color_sensor:
      center: 'ev3-ports:in2'

    touch_sensor:
      left: 'ev3-ports:in1'
      right: 'ev3-ports:in4'

    ultrasonic_sensor:
      front: 'ev3-ports:in3'

    x: 30
    y: 50

obstacles:
  border:
    depth: 30
    color: (59, 60, 54)
    type: 'border'

  lake_blue:
    border_width: 29
    inner_radius: 38
    color: (58, 166, 221)
    x: 500
    y: 170
    type: 'lake'

  lake_green:
    border_width: 29
    inner_radius: 38
    color: (252, 227, 3)
    x: 250
    y: 600
    type: 'lake'

  lake_red:
    border_width: 29
    inner_radius: 38
    color: (201, 45, 57)
    x: 850
    y: 500
    type: 'lake'

  rock1:
    x: 825
    y: 1050
    width: 150
    height: 60
    color: (169, 169, 169)
    angle: 10
    type: 'rock'

  rock2:
    x: 975
    y: 275
    width: 300
    height: 90
    color: (169, 169, 169)
    angle: 130
    type: 'rock'

  bottle:
    x: 500
    y: 500
    radius: 40
    color: (85, 107, 47)
    type: 'bottle'