exec_settings:
  frames_per_second: 60

image_paths:
  body: "../../assets/images/body.png"
  color_sensor: "../../assets/images/color_sensor.png"
  color_sensor_blue: "../../assets/images/color_sensor_blue.png"
  color_sensor_green: "../../assets/images/color_sensor_green.png"
  color_sensor_red: "../../assets/images/color_sensor_red.png"
  touch_sensor_left: "../../assets/images/touch_sensor_left.png"
  touch_sensor_right: "../../assets/images/touch_sensor_right.png"
  ultrasonic_sensor: "../../assets/images/ultrasonic_sensor.png"
  wheel: "../../assets/images/wheel.png"

motor_alloc_settings:
  center_motor: 'OUTPUT_C'
  left_motor: 'OUTPUT_A'
  right_motor: 'OUTPUT_B'

obstacle_settings:
  border_settings:
    border_depth: 10

  lake_settings:
    border_width: 19
    inner_radius: 25
    lake_blue_x: 47
    lake_blue_y: 570
    lake_green_x: 657
    lake_green_y: 333
    lake_red_x: 220
    lake_red_y: 110

screen_settings:
  edge_spacing: 27
  screen_height: 860 # 833 == 1250mm * 2/3 + 27 edge spacing
  screen_width: 860
  screen_title: "Lego ev3dev2 simulator"

wheel_settings:
  circumference: 115

